version: '3'
services:
  app:
    container_name: aplicacionWeb
    build: 
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - 8089:8089
    volumes:
      - 